language: python

python:
  - "3.4"
  - "3.6"

install:
  - sudo apt-get install libpq-dev python3-dev
  - pip install --upgrade pip
  - pip install -e .[dev]

script:
  - python manage.py makemigrations
  - python manage.py migrate
