version: '2.1'
services:
# Nginx proxy server. It will serve static files and redirect all other
# requests to the Django Codeschool application. Both containers communicate
# using a TCP connection on port 8000.
    nginx:
        image: nginx:1.11
        container_name: nginx_proxy
        volumes:
            - $PWD/docker/nginx.conf:/etc/nginx/nginx.conf
            - $PWD/collect/media/:/var/www/media/
            - $PWD/collect/static/:/var/www/static/
            - $PWD/docker/sock/:/tmp/sock/
        depends_on:
            - webapp
        ports:
            - '80:80'


# Codeschool app serves the dynamic pages. It has to communicate with the
# underlying services using the default ports.
    webapp:
        build: .
        container_name: codeschool-app
        volumes:
            - $PWD/collect/media/:/app/collect/media/
            - $PWD/src/:/app/src/
            - $PWD/log/:/app/log/
            - $PWD/docker/volumes/db/:/app/db/
            - $PWD/docker/sock/:/tmp/sock/
        environment:
            - CODESCHOOL_PRODUCTION=true
            - REDIS_SERVER=redis
            - LANG=C.UTF-8
        depends_on:
            - redis
        links:
            - redis
        command: bash -l -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn codeschool.wsgi -b unix:///tmp/sock/webapp.sock --reload -w 4 && python3 manage.py runserver"
        tty: true


# Redis database
    redis:
        image: redis:3
        container_name: redis_db
        volumes:
            - $PWD/docker/volumes/redis/:/data/
        ports:
            - '5000:6379'
