 version: '2'
 services:
   nginx:
     image: nginx:mainline-alpine
     volumes:
       - ./docker/nginx.conf:/etc/nginx/nginx.conf
       - ./collect/media/:/var/www/media/
       - ./collect/static/:/var/www/static/
       - ./docker/sock/:/tmp/sock/
     depends_on:
       - web
     ports:
       - '80:80'
   web:
     build: .
     command: /bin/bash -l -c "python3 manage.py makemigrations && python3 manage.py migrate && python manage.py runserver 0.0.0.0:3000"
     ports:
       - '3000:3000'
     volumes:
       - .:/code
     environment:
       - REDIS_SERVER=redis
     depends_on:
       - redis
     links:
       - redis
   redis:
     image: redis:alpine
