# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0004_auto_20170610_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKeySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False, help_text='Verify if the answer key source is validated', verbose_name='is validated?')),
                ('source', models.TextField(blank=True, help_text='Source code for the correct answer in the given programming language.', verbose_name='answer source code')),
                ('error_message', models.TextField(blank=True, help_text='If an error is found on post-validation, an error message is stored in here.', verbose_name='error message')),
                ('source_hash', models.CharField(default='d41d8cd98f00b204e9800998ecf8427e', help_text='Hash computed from the reference source', max_length=32)),
            ],
            options={
                'verbose_name': 'answer key source',
                'verbose_name_plural': 'answer keys source',
            },
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='source',
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='source_hash',
        ),
    ]
