# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding_io', '0005_auto_20170620_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='answerKeySource',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='coding_io.AnswerKeySource'),
            preserve_default=False,
        ),
    ]
